/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Session
         * @description Ouvre le navigateur visible sur instagram.com : l'utilisateur s'y connecte lui-même.
         */
        post: operations["start_session_api_session_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Status
         * @description Indique si le navigateur est ouvert et si l'utilisateur est connecté (à interroger
         *     régulièrement pendant la connexion manuelle).
         */
        get: operations["session_status_api_session_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Ferme le navigateur et supprime son profil local, donc la session Instagram.
         */
        delete: operations["delete_session_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Data
         * @description Supprime toutes les données locales d'IUC (profil, base, rapports, diagnostics,
         *     journaux), puis repart d'une base vide.
         */
        delete: operations["delete_data_api_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jobs */
        get: operations["get_jobs_api_jobs_get"];
        put?: never;
        /**
         * Create Cleanup
         * @description Crée un nettoyage et lance en arrière-plan la collecte de son aperçu (rien n'est
         *     retiré). Suivre l'avancement avec GET /api/jobs/{id}/events.
         */
        post: operations["create_cleanup_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Items
         * @description Likes ciblés, dans l'ordre de la grille, page par page.
         */
        get: operations["get_items_api_jobs__job_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Items
         * @description Décoche (exclut) ou recoche des likes de l'aperçu.
         */
        patch: operations["patch_items_api_jobs__job_id__items_patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Cleanup
         * @description Lance les unlikes. Le premier lancement valide l'aperçu.
         */
        post: operations["start_cleanup_api_jobs__job_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Cleanup
         * @description Reprend un nettoyage en pause, là où il s'était arrêté.
         */
        post: operations["resume_cleanup_api_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Cleanup
         * @description Demande une pause : le lot en cours se termine, est contrôlé, puis tout s'arrête.
         */
        post: operations["pause_cleanup_api_jobs__job_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Cleanup
         * @description Arrête définitivement un nettoyage : les likes non traités ne seront pas retirés.
         *     En cours d'exécution, l'arrêt a lieu après le lot en cours ; une collecte d'aperçu en
         *     cours est interrompue.
         */
        post: operations["stop_cleanup_api_jobs__job_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description Progression en direct (Server-Sent Events) : « snapshot », puis « status »,
         *     « progress », « batch » et enfin « end ». Le jeton peut être passé en paramètre
         *     `token`, car EventSource ne sait pas envoyer d'en-tête.
         */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Report
         * @description Rapport du nettoyage, en JSON ou en CSV ; les fichiers sont aussi écrits dans
         *     DATA_DIR/reports.
         */
        get: operations["job_report_api_jobs__job_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Authors
         * @description Comptes dont tu as aimé des publications, d'après tes aperçus déjà collectés (ceux du
         *     compte connecté s'il est connu), du plus fréquent au moins fréquent. Liste vide avant le
         *     premier aperçu.
         */
        get: operations["get_authors_api_authors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthorOut */
        AuthorOut: {
            /** Author */
            author: string;
            /**
             * Likes
             * @description Likes encore en place, d'après les aperçus collectés.
             */
            likes: number;
        };
        /**
         * CleanupFilters
         * @description Critères d'un nettoyage.
         *
         *     Le tri et les dates sont appliqués par Instagram, avec le filtre de la page des likes.
         *     Le type et les auteurs sont appliqués par IUC sur les vignettes collectées, car la
         *     version web d'Instagram ne propose pas ces filtres. Quand un critère ne peut pas être
         *     vérifié pour un like (auteur ou type illisible), le like est gardé.
         */
        CleanupFilters: {
            /** @default newest_first */
            sort: components["schemas"]["SortOrder"];
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** @default all */
            content: components["schemas"]["ContentFilter"];
            /**
             * Include Authors
             * @default []
             */
            include_authors: string[];
            /**
             * Exclude Authors
             * @default []
             */
            exclude_authors: string[];
        };
        /**
         * ContentFilter
         * @enum {string}
         */
        ContentFilter: "all" | "posts" | "reels";
        /** DeletedOut */
        DeletedOut: {
            /** Deleted */
            deleted: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemOut */
        ItemOut: {
            /** Id */
            id: number;
            /**
             * Rank
             * @description Rang dans l'aperçu, à partir de 1.
             */
            rank: number;
            /** Media Key */
            media_key: string;
            /** Label */
            label: string;
            /** Author */
            author: string | null;
            media_kind: components["schemas"]["MediaKind"] | null;
            /**
             * Shared On
             * @description Date « partagée le » affichée par Instagram.
             */
            shared_on: string | null;
            status: components["schemas"]["ItemStatus"];
            /** Error */
            error: string | null;
            /** Processed At */
            processed_at: string | null;
        };
        /**
         * ItemStatus
         * @enum {string}
         */
        ItemStatus: "pending" | "selected" | "excluded" | "done" | "failed" | "skipped";
        /** ItemsPage */
        ItemsPage: {
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** ItemsPatch */
        ItemsPatch: {
            /** Item Ids */
            item_ids: number[];
            /**
             * Excluded
             * @description true : décocher (exclure) ; false : recocher.
             */
            excluded: boolean;
        };
        /** ItemsPatchOut */
        ItemsPatchOut: {
            /** Changed */
            changed: number;
            job: components["schemas"]["JobOut"];
        };
        /**
         * JobCreate
         * @description Critères du nettoyage, et limite facultative de vignettes à lire (pour un essai).
         */
        JobCreate: {
            /** @default newest_first */
            sort: components["schemas"]["SortOrder"];
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** @default all */
            content: components["schemas"]["ContentFilter"];
            /**
             * Include Authors
             * @default []
             */
            include_authors: string[];
            /**
             * Exclude Authors
             * @default []
             */
            exclude_authors: string[];
            /** Max Scanned */
            max_scanned?: number | null;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: number;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Account Id */
            account_id: string | null;
            filters: components["schemas"]["CleanupFilters"];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** To Process */
            to_process: number;
            /**
             * Running
             * @description Une tâche de ce nettoyage tourne en ce moment.
             */
            running: boolean;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "created" | "collecting" | "ready" | "running" | "paused" | "completed" | "stopped" | "failed";
        /**
         * MediaKind
         * @description Type de publication, tel que l'indique le libellé de la vignette.
         * @enum {string}
         */
        MediaKind: "photo" | "video" | "carousel";
        /** SessionStatusOut */
        SessionStatusOut: {
            /** Browser Open */
            browser_open: boolean;
            /** Logged In */
            logged_in: boolean;
            /** Account Id */
            account_id: string | null;
            /**
             * Page
             * @description Nature de la page affichée (accueil, connexion...).
             */
            page: string | null;
            /** Challenge Required */
            challenge_required: boolean;
            /** Consent Required */
            consent_required: boolean;
            /**
             * Busy
             * @description Une collecte ou un nettoyage est en cours.
             */
            busy: boolean;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "newest_first" | "oldest_first";
        /** StartRequest */
        StartRequest: {
            /**
             * Limit
             * @description Nombre maximal de likes à retirer pendant cette exécution.
             */
            limit?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_session_api_session_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_status_api_session_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_data_api_data_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_cleanup_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_items_api_jobs__job_id__items_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ItemStatus"] | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_items_api_jobs__job_id__items_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemsPatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_cleanup_api_jobs__job_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_cleanup_api_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_cleanup_api_jobs__job_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_cleanup_api_jobs__job_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_report_api_jobs__job_id__report_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_authors_api_authors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
